name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Setup Biome
      #   uses: biomejs/setup-biome@v2
      #   with:
      #     version: latest
      # - name: Run Biome
      #   run: biome ci src

      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Run Biome
        run: npm run lint